### ISSUE TITLE
Archive maplibre-java

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-java#1]
@petr-pokorny-1, this repo seems to be inactive. Can we archive it?

**Comment by wipfli** [comment]
#2

**Comment by thehoneymad** [comment]
@wipfli What are consequences of archiving. Some of the maven packages this library builds are published to maven and used by the Android SDK directly from maven.

**Comment by wipfli** [comment]
I did not understand that this repo was used in native shen writing this issue. I thunk we can just close it ...
