### ISSUE TITLE
Build a formal release process

### ISSUE THREAD

**Issue by thehoneymad** [maplibre/maplibre-java#13]
This library is missinga  formal release process. The last release to Maven Central was 5.9.0 on April 2021. This is a required library for building MapLibre Android SDK.

### Acceptance Criteria
A formal release process is established. This should be a small markdown document describing how to cut a release. In the end we want to have a release process that does the following:

1. Initiate a formal Release when a release document is cut from Github
2. Automated changelog.md update resulted from a release
3. Release artifact to Maven Central
4. Release artifact to Github Packages
5. Release artifact as a noted release in GIthub Releases section

**Comment by louwers** [comment]
This is now done. Although the artifact is not uploaded to GitHub.
