### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-java#14]
This repository has currently 61 branch. I think it would be best to remove all the stale and unused branches. @thehoneymad I saw you suggest using a `main` branch for stable things and a `develop` branch for ongoing work. In all the other MapLibre GitHub repos I think we take the approach to just have one `main` branch and make sure that this one is always passing CI and that we can cut releases from the main branch at any point in time.

With your kind permission I would like to do the same thing here: just have one `main` branch and make sure that this one is in good shape.

Development of pull requests should ideally happen in the forks of the contributors. I think this helps a bit for new people to contribute because then the process for contributions is the same for everyone (people with and without write access to this repo)...

**Comment by thehoneymad** [comment]
That is okay. But there's a consequence to that. I was following tried and tested gitflow. 

The problem with main releases cutting is not having nearly fully automated releases. You always need syncing between teams for major refactors and that gets tricky. :)

I will move the process to having main be the branch for release. Our goal now is having

1. Snapshot builds and releases if there's a new change.
2. Automated nightlies.
3. Fully automated releases with release notes, changelog, and artifact publishing.

I think I will keep 1 and 3. :) If I have snapshot builds from main, I won't need nightlies. :)

**Comment by thehoneymad** [comment]
And on remote branches, yeah it's a bit of a grunt work. But it's okay. :) That's another day at AWS. :P

We will get it there.

**Comment by thehoneymad** [comment]
I have started working on it on #5
