### ISSUE TITLE
Upstream consumers build

### ISSUE THREAD

**Issue by thehoneymad** [maplibre/maplibre-java#15]
#### Context
MapLibre-Java provides utility libraries for MapLibre Android SDK. If a new feature is released or something new is written for MapLibre-Java, we need to ensure we do not break the MapLibre Android SDK.

### Acceptance Criteria
1. MapLibre-Java continuous build and release process MUST build MapLibre Android SDK to ensure compatibility.

This could be achieved with a workflow in MapLibre-Java or through other mechanisms. The goal is to have a mechanism to not have breaking changes.

**Comment by louwers** [comment]
The utilities this library provides can be unit tested.

It is OK if a new version of this library temporarily cannot be used with MapLibre Native, which will be the case if we change the package prefix from `com.mapbox` to `org.maplibre` for example.

A daily dependency check runs in `maplibre/maplibre-native`. If a new version of these utilities is released, a PR to update is automatically created and the CI checks are run. If something broke, we will know right away and we can fix it quickly.

Closing for now, I think this is a good solution.
