### ISSUE TITLE
Triage hanging remote branches

### ISSUE THREAD

**Issue by thehoneymad** [maplibre/maplibre-java#5]
There are a lot of hanging branches in the remote. Some of them contains incomplete feature works like `turf-center`. This task is about to triage these branches.

We expect to have one of 2 possible outcomes for these branchs
1. Remove the branch if it is too old.
2. If there are incomplete feature work, keep the branch.

For branches that falls in number 2, we will do a second round of triaging.

**Comment by wipfli** [comment]
We could also just checkout the entire git repo with all branches, pack the folder into a tar file and upload everything here to this issue. Then we would have a backup of the old code.

It just seems so hard to go through all that old work and triage things out. I doubt that we will find much valuable stuff there...

**Comment by thehoneymad** [comment]
Yeah we can `git bundle` it. But my opinion here would be not to do it.

Because honestly we will never get to it. 61 branches is a lot. But not a lot lot. We have a task on AWS side to fix it. Will get it done. :)

**Comment by wipfli** [comment]
Cool!

**Comment by thehoneymad** [comment]
Started working on this one.

**Comment by thehoneymad** [comment]
Back on this. Cleanup continues!

**Comment by thehoneymad** [comment]
Cleanup complete! I kept some branches alive that has turf changes. I am looking into them. Will cut an issue and then close this.

**Comment by thehoneymad** [comment]
All branch cleaned up! :)
